name: CI Pipeline

# Cuando se ejecuta el flujo de trabajo
on:
  push:
    branches:
      - main  # El flujo se activa cuando se hace un push en la rama main
  pull_request:
    branches:
      - main  # También se activa cuando se abre un pull request hacia la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # El trabajo se ejecutará en un entorno de Ubuntu más reciente

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v2  # Acción para obtener el código del repositorio

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # La versión de Node.js que deseas usar

      # Paso 3: Instalar las dependencias del proyecto
      - name: Install dependencies
        run: npm install  # Instalar las dependencias definidas en package.json

      # Paso 4: Ejecutar pruebas
      - name: Run tests
        run: npm test  # Ejecutar las pruebas definidas en el proyecto
